DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE item (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  found TIMESTAMP,
  description TEXT NOT NULL,
  image_path TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  owner INTEGER,
  FOREIGN KEY (owner) REFERENCES user (id)
);