

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE item (
  number INTEGER PRIMARY KEY AUTOINCREMENT,
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  found_time TIMESTAMP,
  used_time TIMESTAMP,
  description TEXT NOT NULL,
  image_path TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  owner INTEGER,
  FOREIGN KEY (owner) REFERENCES user (id)
);