version: '3.8'

services:
  qrapi:
    image: qrapi:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY
    volumes:
      - ../instance:/app/instance