version: '3.8'

services:
  qrapi:
    image: qrapi:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY="\xb3\x13\njr\xb59\xb3]\xdbi^;\rr\xbe\xacn\x9ce\xeb\xe8&G"
    volumes:
      - ../instance:/app/instance