name: Simple-API Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag simple-api:latest
        docker push ghcr.io/patrickcooper95/simple-api:latest
