name: Simple-API Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_image:

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/patrickcooper95/simple-api:latest
        docker push ghcr.io/patrickcooper95/simple-api:latest
